### ISSUE TITLE
Non-interactive use

### ISSUE THREAD

**Issue by DennisMitchell** [Azer0s/HadesLang#146]
I've been trying to add Hades to [TIO], but I can't figure out how to use it non-interactively.

After compiling the interpreter (with `dotnet publish HadesLang/HadesLang.csproj -c Release -r linux-x64 --self-contained`), trying to run the built executable (`HadesLang/bin/Release/netcoreapp2.0/linux-x64/publish/HadesLang`) produces the following output.

```
__ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  









                           /--
                           +:      .-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  









                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  








                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  







                            /:--`.-::
                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  






                            :::---::+
                            /:--`.-::
                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  





                              ::::/:
                            :::---::+
                            /:--`.-::
                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  




                               :::-
                              ::::/:
                            :::---::+
                            /:--`.-::
                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     =======================================================

        __ __           __             __                    
       / // / ___ _ ___/ / ___   ___  / /  ___ _  ___   ___ _
      / _  / / _ `// _  / / -_) (_-< / /__/ _ `/ / _ \ / _ `/
     /_//_/  \_,_/ \_,_/  \__/ /___//____/\_,_/ /_//_/ \_, / 
                                                      /___/  


                                /:+
                                ::-
                               :::-
                              ::::/:
                            :::---::+
                            /:--`.-::
                            ::-..`.::
                           /--..```.-+
                           +:.`````.-+
                             +:--..:/


     =======================================================
     ||                   Hades - v0.4                    ||
     ||                   Press any key...                ||
     =======================================================
Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at Colorful.Console.ReadKey()
   at Interpreter.ShellInterpreter.PrintStart(Decimal version) in /opt/hades/Interpreter/ShellInterpreter.cs:line 263
   at Interpreter.ShellInterpreter..ctor(String path) in /opt/hades/Interpreter/ShellInterpreter.cs:line 20
   at HadesLang.Program.Main(String[] args) in /opt/hades/HadesLang/Program.cs:line 20
```

[TIO]: https://tio.run

**Comment by Azer0s** [comment]
Thanks for adding Hades to TIO!
This was indeed a bug and was not supposed to happen. Anyway...I fixed it. (#147)
You can now execute a HadesScript from a file with the command
`dotnet HadesLang.dll filename`

**Comment by DennisMitchell** [comment]
https://tio.run/#hades

Thank you for the quick fix!
